### PR TITLE
Added AptChat template

### PR DESCRIPTION
**Pull request by apt-team-018**

### CODE REVIEW

**Comment by winglian** [comment]
@code-x-0018 @Arpitsh018 You exposed your AWS credentials in this PR so they've been compromised now, you should invalidate this ASAP. https://github.com/OpenAccess-AI-Collective/axolotl/pull/870/files#diff-be8f2a642a9a3669e03bfca00762f4486c0d2cebccc4bf89fbbecb5b0c1db3f2R367

**Comment by winglian** [comment]
@code-x-0018 @Arpitsh018 same for your GitHub credentials https://github.com/OpenAccess-AI-Collective/axolotl/pull/870/files#diff-be8f2a642a9a3669e03bfca00762f4486c0d2cebccc4bf89fbbecb5b0c1db3f2R10

**Comment by apt-team-018** [comment]
Thanks for highlighting, I will fix it

**Comment by NanoCode012** [comment]
Hello, thanks for the PR. 

Edit: Please ignore the following. Looking at the latest commits, I don't believe the below is possible.

---

Hm, I don't think this requires an entire script. You could possibly just do a role remap like below.

https://github.com/OpenAccess-AI-Collective/axolotl/blob/71b7ea3c056f15123b56fef3151b4044c80078b4/src/axolotl/prompt_strategies/sharegpt.py#L87-L96

I think we can clean up the PR by remove ds_store and the notebook. If you're interested in adding a notebook, it would be highly appreciated if this can be done in a separate PR.

**Pull request closed without merging**
