### PR TITLE
csv to jsonl

### PR DESCRIPTION
**Pull request by Shubin-vadim**
# Description

Added functionality to convert .csv files to .jsonl format, as the .csv format is one of the most widely used for data storage and exchange. This allows easy integration of CSV data into the Axolotl system.

## Motivation and Context

The .csv format is one of the most common formats for handling data. Adding conversion functionality to .jsonl makes the system more flexible and user-friendly for those who need to work with CSV files.

## How has this been tested?

The changes have been tested by converting various .csv files to .jsonl format using real data. The results of the conversion were checked for correctness and conformance to the expected structure.

## Screenshots (if appropriate)

None.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Social Handles (Optional)

None.

### CODE REVIEW

**Comment by NanoCode012** [comment]
Hello, thanks for the PR. We currently support `.csv` via `datasets.load_dataset` method. Is there some new functionality I'm missing?

```yaml 
    - path: data.csv
      ds_type: csv
      type: alpaca
```

**Comment by NanoCode012** [comment]
Hey @Shubin-vadim , may I ask if you tried my suggestion in the earlier comment? It should solve your initial issue.

**Comment by Shubin-vadim** [comment]
> Hey @Shubin-vadim , may I ask if you tried my suggestion in the earlier comment? It should solve your initial issue.

Yes, your solution helped. Could you please let me know if your solution to my question is described in the documentation? If so, could you please share the link? I would like to share it with my colleagues.

**Comment by NanoCode012** [comment]
Here is the line specific doc (otherwise, it's the `config` page on our doc): https://github.com/axolotl-ai-cloud/axolotl/blob/db51a9e4cb640552ebb8e178139a31b9bcdc5e98/docs/config.qmd#L88 

We're trying to improve the docs to explain our configs better.

**Comment by Shubin-vadim** [comment]
Thank you)

**Pull request closed without merging**
