### PR TITLE
Added Orca Mini prompt strategy

### PR DESCRIPTION
**Pull request by jphme**
I successfully finetuned orca mini with these setting, as you mentioned you are interested in contributions for `prompt_strategies` i figured i could also open a PR for that, because the prompt template is different from the recently merged Open Orca format.

Will also try to work on Vicuna which is much more complicated due to masking/tokenizing...

### CODE REVIEW

**Review by winglian — APPROVED** [review]
lgtm, thanks!

**Comment by winglian** [comment]
@jphme could you run `pre-commit run --all-files` to catch any pre-commit lint issues pls? thanks!

**Comment by jphme** [comment]
> pre-commit run --all-files

did so, sorry (originally implemented the prompt stratgies only for myself and didn't plan to PR them; so didn't install dev recs)!

**Comment by NanoCode012** [comment]
Thank you! Sorry for the late merge.

**Pull request merged**
