### PR TITLE
Update XFormers Attention Monkeypatch to handle Llama-2 70B (GQA)

### PR DESCRIPTION
**Pull request by ssmi153**
This is a fix for this issue: https://github.com/OpenAccess-AI-Collective/axolotl/issues/338 . It fixes the XFormersAttention monkeypatch. I've tested this with LLama-2 70B and Llama-2 13B and both are able to start training appropriately without any errors. 

Notes: 
1) I haven't yet tested this with an complete finetune from start to finish - this will take a number of days to complete.
2) We still also need to fix the FlashAttention monkeyscript. I've been working on this but have run into a number of errors, so I'm pushing this out in the meantime.

### CODE REVIEW

**Comment by ssmi153** [comment]
Maybe hold off on committing this - I just found that while it runs LLama-2-13b properly, the losses are completely different (starts at 8 rather than starting at 1). I need to look more closely into why this is, as it shouldn't be changing anything for the 13B model.

**Comment by ssmi153** [comment]
OK, this most recent commit fixes the difference in losses. It was a whitespace issue - darn Python! This now performs exactly like it did previously for 13B (and 7B) models without GQA, and also now works for 70B models with GQA. It's ready for review and merging.

**Review by winglian — APPROVED** [review]
thank you!

**Comment by winglian** [comment]
@ssmi153 looks like there are some pre-commit formatting issues. `pre-commit run --all-files` should fix it

**Comment by ssmi153** [comment]
OK, I'll look into this. Struggling to get pre-commit to work on Windows at
the moment. I'll sort this out as soon as I can.

**Comment by winglian** [comment]
@ssmi153 you could cherry-pick this commit https://github.com/OpenAccess-AI-Collective/axolotl/commit/9793faf6dc0c68908aee620c6dbe3a18322861c7

**Comment by ssmi153** [comment]
Champion! I've pulled your changes into the pull request (in probably in the most awkward possible way, sorry - it's been a few years since I last commited code, and our last setup used mercurial, so I'm just getting my head around Github's workflows).

**Comment by winglian** [comment]
Thanks @ssmi153. This is very much appreciated and wanted.

**Pull request merged**
