### PR TITLE
Added "epoch" evaluation_strategy

### PR DESCRIPTION
**Pull request by flotos**
Enable running eval on epoch count instead of steps

### CODE REVIEW

**Comment by NanoCode012** [comment]
Hey! I would prefer extracting this into its own section/variable than doing two ifs like that for readability.

**Comment by teknium1** [comment]
Hello this is not working for me

**Comment by flotos** [comment]
The current parameter is a bit weird (hence why they planned a refactor I think) because it will save every epoch if the number is below 1, and will ignore the number you used. (it won't save every 0.2 epoch if that's the number you used for example).
Did it not work even after 1 epoch?

**Comment by ehartford** [comment]
I would be happy to use a 0.2 epoch setting

**Comment by flotos** [comment]
According to HF trainer this can't be done with basic Trainers arguments : https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.evaluation_strategy

So we would need to calculate an `eval_step = (trainDatasetSize / batch_size) * cfg.eval_step` if we are using an epoch strategy.
However I don't know how micro_batch_size work and if it would affect the above calculation, or if other parameters too.

**Comment by NanoCode012** [comment]
> According to HF trainer this can't be done with basic Trainers arguments : https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.evaluation_strategy
> 
> So we would need to calculate an `eval_step = (trainDatasetSize / batch_size) * cfg.eval_step` if we are using an epoch strategy. However I don't know how micro_batch_size work and if it would affect the above calculation, or if other parameters too.

Hello, I think this may not be true. This PR has a bit weird logic as said and there is a follow up PR addressing this #403 .

> eval_steps: If smaller than 1, will be interpreted as ratio of total training steps.
https://huggingface.co/docs/transformers/main_classes/trainer#transformers.TrainingArguments.eval_steps

This may be what @ehartford wanted.

**Pull request merged**
