### PR TITLE
Added chatglm3 conversation type for training models like TinyLLama

### PR DESCRIPTION
**Pull request by xaviviro**

### CODE REVIEW

**Comment by NanoCode012** [comment]
Hey! Thanks for PR. Could you run this through the linter also?

**Comment by xaviviro** [comment]
Hi there, I've run the code through Pylint and made a couple of minor spacing adjustments as suggested by the tool. Please let me know if there's anything else that needs to be addressed for this PR. Thank you!

**Comment by NanoCode012** [comment]
Leaving this here for reference implementation: https://github.com/lm-sys/FastChat/blob/722ab0299fd10221fa4686267fe068a688bacd4c/fastchat/conversation.py#L169-L178

I find it weird that there's a space before `message` since I don't see it within their docs, but fschat has it.

https://github.com/THUDM/ChatGLM3/blob/main/PROMPT_en.md

**Comment by xaviviro** [comment]
You're right, I have copied the code from https://github.com/lm-sys/FastChat/blob/main/fastchat/conversation.py

I've run a train and the fine-tuned model seems to be working incredibly well.

**Review by NanoCode012 — APPROVED** [review]

**Comment by NanoCode012** [comment]
Thank you for the PR!

**Pull request merged**
