### PR TITLE
Add example Llama 2 ReLoRA config

### PR DESCRIPTION
**Pull request by cg123**
As per #470, adds an example configuration file that I've used to test locally on a 3090.

### CODE REVIEW

**Comment by mhenrichsen** [comment]
Looks good. Maybe default to a smaller dataset?

I'm not sure if `paged_adamw_32bit` is the way to go.

Edit:
You also mentioned that you only tested with `adamw_bnb_8bit` in the PR. Has this changed?

**Comment by cg123** [comment]
Ah yes, good point - I have tested it with `paged_adamw_32bit` as well now, and it works fine. Happy to change it if you think there's a better default here though.

As for the smaller dataset: I purposefully chose this one as being on the smaller side of what I would use recommending ReLoRA with, as there need to be enough steps to get a few restarts in before you start to see any benefit. A smaller dataset would definitely be fine for just testing that you can run ReLoRA at all though, if that's more useful?

**Comment by mhenrichsen** [comment]
Sounds good.
I get the idea behind using a larger dataset to see the benefits of ReLoRA. 
Personally I've used smaller datasets to test that it can complete multiple epochs, saves and evaluates without running out of VRAM. Using a larger dataset would make those take longer time.

**Review by NanoCode012 — APPROVED** [review]

**Comment by cg123** [comment]
I have been struck down for my hubris. `paged_adamw_32bit` does not, in fact, work fine in all configurations.

Switched to `adamw_bnb_8bit` for the example.

**Comment by ehartford** [comment]
That is great to know!  Thank you for your excellent work!

**Review by tmm1 — APPROVED** [review]

**Pull request merged**
