### PR TITLE
refactor: prompter

### PR DESCRIPTION
**Pull request by Thytu**
* Set system prompts as private attributes
* Rename `*AlpacaPrompter.match_prompt_style` as `*AlpacaPrompter.__init_prompt_template`
* `*AlpacaPrompter.__init_prompt_template` will now raise a `ValueError` if an invalide prompte style is provided

I will submit small PRs (instead of a single big one) in order to make it easier for you to review.

### CODE REVIEW

**Comment by NanoCode012** [comment]
Hey, thanks for PR. I would like to point out some parts.

- `src/axolotl/prompters.py` : since you have modified the local variable. Classes that inherit the base require change as well
- `src/axolotl/prompt_strategies/creative_acr.py` <- You would also need to rename `system_prompt`
- ~I am not sure whether `raise ValueError(f"Received an unknown prompt style ({self.prompt_style})")` would work for all scenarios. For example, the `CompletionPrompter` does not require a prompt style. One alternative would be to not inherit `AlpacaPrompter` anymore.~ Fixed in #88

**Review by winglian — APPROVED** [review]
looks good to me, let me see if I can validate it

**Comment by winglian** [comment]
Also, would you mind rebasing this against main? I added a unit test for the original behavior for this feature. https://github.com/OpenAccess-AI-Collective/axolotl/pull/87

thanks!

**Comment by Thytu** [comment]
Didn't see that you're using inheritance from `AlpacaPrompter`, it thus need to be changed from private (`__foo`) to protected (`_foo`).

**Comment by Thytu** [comment]
Cleaning my PR history

**Pull request closed without merging**
