### PR TITLE
fix: Dockerfile - pin deepspeed to 0.11.2

### PR DESCRIPTION
**Pull request by fpreiss**
# Description

Dockerfile-base:  pin deepspeed to 0.11.2

## Motivation and Context

Deepspeed update to  0.12.x breaks building docker of image.

Since today trying to build the docker base image with:

```bash
git clone https://github.com/OpenAccess-AI-Collective/axolotl.git
cd axolotl/docker
docker buildx build -f Dockerfile-base --target base-builder -t base-builder --progress=plain .
docker buildx build -f Dockerfile-base --target deepspeed-builder -t deepspeed-builder --progress=plain .
```

leads to the following error:

```text
 > [deepspeed-builder 2/2] RUN git clone https://github.com/microsoft/DeepSpeed.git &&     cd DeepSpeed &&     MAX_CONCURRENCY=8 DS_BUILD_SPARSE_ATTN=0 DS_BUILD_OPS=1 DS_BUILD_EVOFORMER_ATTN=0 python3 setup.py bdist_wheel:
32.02  [WARNING]  cpu_lion attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
32.02  [WARNING]  cpu_lion attempted to use `py-cpuinfo` but failed (exception type: <class 'UnboundLocalError'>, local variable 'get_cpu_info' referenced before assignment), falling back to `lscpu` to get this information.
32.02  [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
32.02  [WARNING]  Filtered compute capabilities ['7.0', '7.5']
32.02     ext_modules.append(builder.builder())
32.02   File "/workspace/DeepSpeed/op_builder/builder.py", line 633, in builder
32.02     extra_link_args=self.strip_empty_entries(self.extra_ldflags()))
32.02   File "/workspace/DeepSpeed/op_builder/inference_cutlass_builder.py", line 71, in extra_ldflags
32.02     import dskernels
32.02 ModuleNotFoundError: No module named 'dskernels'
```

## How has this been tested?

The changes have been tested manually on my local machine with the two docker build commands above.

### CODE REVIEW

**Comment by casper-hansen** [comment]
This PR should not be needed. 

pip install deepspeed-kernels

https://github.com/microsoft/DeepSpeed-Kernels

**Comment by fpreiss** [comment]
Thank you, I can verify, that with the following patch I can indeed build both - the `Dockerfile-base`, as well as the `Dockerfile` (from the local base image) on the deepspeed `v0.12.2` tag.
```diff
 RUN python3 -m pip install --upgrade pip && pip3 install packaging && \
-    python3 -m pip install --no-cache-dir -U torch==${PYTORCH_VERSION}+cu${CUDA} --extra-index-url https://download.pytorch.org/whl/cu$CUDA
+    python3 -m pip install --no-cache-dir -U torch==${PYTORCH_VERSION}+cu${CUDA} deepspeed-kernels --extra-index-url https://download.pytorch.org/whl/cu$CUDA
```

**Comment by winglian** [comment]
> Thank you, I can verify, that with the following patch I can indeed build both - the `Dockerfile-base`, as well as the `Dockerfile` (from the local base image) on the deepspeed `v0.12.2` tag.
> 
> ```diff
>  RUN python3 -m pip install --upgrade pip && pip3 install packaging && \
> -    python3 -m pip install --no-cache-dir -U torch==${PYTORCH_VERSION}+cu${CUDA} --extra-index-url https://download.pytorch.org/whl/cu$CUDA
> +    python3 -m pip install --no-cache-dir -U torch==${PYTORCH_VERSION}+cu${CUDA} deepspeed-kernels --extra-index-url https://download.pytorch.org/whl/cu$CUDA
> ```

thanks, is it easier to open a new PR for this change or just modify this PR?

**Comment by fpreiss** [comment]
I'll open a new PR

**Pull request closed without merging**
