### PR TITLE
Adding qlora config for Mistral

### PR DESCRIPTION
**Pull request by tokenbender**
Contains fix for Mistral FA issue - ValueError: You are attempting to perform batched generation with padding_side='right' this may lead to unexpected behaviour for Flash Attention version of Mistral. Make sure to  call tokenizer.padding_side  = 'left' before tokenizing the input.

Fix for now is to set sample_packing: true and pad_to_sequence_len: true

### CODE REVIEW

**Comment by tokenbender** [comment]
The workaround can also go in config.yml but I don't think sample_packing: true/pad_to_sequence_len: true should be forced on the default full FT config.

**Comment by seungduk-yanolja** [comment]
can we just add a config to set padding_side: left?

**Comment by NanoCode012** [comment]
The main issue will be fixed in #681 . However, we can still get this config in :)

**Review by NanoCode012 — COMMENTED** [review]
Could you rename the file to `qlora.yml` to follow the same format as others?

**Comment by tokenbender** [comment]
> Could you rename the file to `qlora.yml` to follow the same format as others?

Done

**Review by NanoCode012 — APPROVED** [review]

**Pull request merged**
