### PR TITLE
auto-versioning and adding axolotl.__version__

### PR DESCRIPTION
**Pull request by djsaunde**
# Description

Small change using `importlib` magic to automagically populate the package version based on `git` tags.

## Motivation and Context

Small QoL improvement for devs and users. Modernizing packaging approach a bit with basic `pyproject.toml`.

## How has this been tested?

On `main` branch:

```shell
# pip install -e .
...
Successfully installed axolotl-0.5.2  # hardcoded version in setup.py, no current commit information

In [1]: from importlib.metadata import version

In [2]: import axolotl

In [3]: axolotl.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 axolotl.__version__

AttributeError: module 'axolotl' has no attribute '__version__'
```

In Runpod, on this branch:

```shell
# pip install -e .
...
Successfully installed axolotl-0.5.3.dev34+gccf7b097  # incremented version with current state (+34 commits) and git hash

# ipython
...
In [1]: from importlib.metadata import version

In [2]: import axolotl

In [3]: axolotl.__version__
Out[3]: '0.5.3.dev34+gccf7b097'
```

## Types of changes

Packaging / package meta improvements.

### CODE REVIEW

**Comment by djsaunde** [comment]
I'd recommend moving fully to `pyproject.toml` at some point, as it's the recommended approach these days. But that's a separate conversation!

**Review by winglian — APPROVED** [review]

**Comment by winglian** [comment]
adding the `pyproject.toml` seems to supersede `setup.py` and breaks the extras

```
WARNING: axolotl 0.1.dev5+g4c60a74 does not provide the extra 'deepspeed'
WARNING: axolotl 0.1.dev5+g4c60a74 does not provide the extra 'flash-attn'
WARNING: axolotl 0.1.dev5+g4c60a74 does not provide the extra 'optimizers'
```

**Comment by winglian** [comment]
okay, I think this is good to go now unless there were additional changes you wanted to add.

**Comment by djsaunde** [comment]
```python
            # Convert `HTTPError` into a `HfHubHTTPError` to display request information
            # as well (request id and/or server error message)
>           raise _format(HfHubHTTPError, str(e), response) from e
E           huggingface_hub.errors.HfHubHTTPError: 503 Server Error: Service Temporarily Unavailable for url: https://huggingface.co/api/datasets/allenai/c4/revision/1588ec454efa1a09f29cd18ddd04fe05fc8653a2

/root/miniconda3/envs/py3.10/lib/python3.10/site-packages/huggingface_hub/utils/_http.py:477: HfHubHTTPError
```
Looks like a flaky test failure (503 service unavailable; happens in both `docker-e2e-tests` tests), will rerun.

**Pull request merged**
