### PR TITLE
Feat: Add tensorboard support

### LINKED ISSUE #763: Support tensorboard
### ⚠️ Please check that this feature request hasn't been suggested before.

- [X] I searched previous [Ideas in Discussions](https://github.com/OpenAccess-AI-Collective/axolotl/discussions/categories/ideas) didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/OpenAccess-AI-Collective/axolotl/labels/enhancement) didn't find any similar feature requests.

### 🔖 Feature description

Support tensorboard as an alternative to wandb.

### ✔️ Solution

Before I started using axolotl I swore never to use wandb again. Needs access to server, annoying retry loop that sometimes breaks, doesn't log all steps and misses spikes. I was just reminded that I'd like to use tensorboard when it couldn't save the trained model because no memory left on device (wandb .cache folder is 500GB).

### ❓ Alternatives

_No response_

### 📝 Additional Context

_No response_

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this feature has not been requested yet.
- [X] I have provided enough information for the maintainers to understand and evaluate this request.

### PR DESCRIPTION
**Pull request by NanoCode012**
Should close #763 

Untested, but should work.

### CODE REVIEW

**Review by winglian — APPROVED** [review]

**Comment by winglian** [comment]
based on the docs, perhaps we should convert this to `None` if it's empty? that way it should default back to the `all` case if not setup
```
report_to (str or List[str], optional, defaults to "all") — The list of integrations to report the 
results and logs to. Supported platforms are "azure_ml", "clearml", "codecarbon", 
"comet_ml", "dagshub", "flyte", "mlflow", "neptune", "tensorboard", and "wandb". Use 
"all" to report to all integrations installed, "none" for no integrations.
```

**Comment by ein-ich** [comment]
Ok I tested it and it works; but I realized it even works on main and without `tensorboard: true`. It seems it always created a tensorboard `runs` logdir in `output_dir`, and I just never noticed?

**Comment by winglian** [comment]
> Ok I tested it and it works; but I realized it even works on main and without `tensorboard: true`. It seems it always created a tensorboard `runs` logdir in `output_dir`, and I just never noticed?

Maybe it never did that until you installed the tensorboard package?

**Comment by ein-ich** [comment]
Yes you're right, it only creates the logs when tensorboard is installed.

**Comment by NanoCode012** [comment]
> Ok I tested it and it works; but I realized it even works on main and without `tensorboard: true`. It seems it always created a tensorboard `runs` logdir in `output_dir`, and I just never noticed?

Hmm, that's weird. It should've been `report_to=None` if not using wandb, which according to the docs would not have any integration. Maybe tensor board logs are just defaulted? In such a case, is this PR needed?

**Comment by ein-ich** [comment]
grafik
(from https://huggingface.co/docs/transformers/v4.34.1/en/main_classes/callback)

**Comment by winglian** [comment]
Yeah, I think the only thing we need is to add tensorboard to the `requirements.txt` or to document that people should install it if wanted. I'm leaning towards just installing it with requirements or maybe with an extras like `pip install -e .[tensorboard]`

**Comment by NanoCode012** [comment]
Closed in favor of adding tensorboard to requirements

**Comment by fakerybakery** [comment]
Hi, sorry I'm a bit confused, how do I use Tensorboard in Axolotl then?

**Comment by NanoCode012** [comment]
@fakerybakery , you can just train normally without setting wandb configs or setting it to disabled

**Pull request closed without merging**
