### PR TITLE
standardize attn hijack patches

### PR DESCRIPTION
**Pull request by tmm1**
all three monkeypatch files now follow the same format and comment structure

you can diff the implementations to see whats different, using `diff -uNdr` or `vim -d`

### CODE REVIEW

**Comment by winglian** [comment]
I've tested the flash-attn variant, but not xformers or sdp yet. That one looked fine

**Comment by ehartford** [comment]
This is really nice.  Thank you so much.

**Comment by ehartford** [comment]
I was curious did we just switch from flash attention 1 to flash attention 2, or do we support either one?  (some people use flash attention 1 because it's more stable, they are still fixing bugs in flash attention 2)

**Comment by tmm1** [comment]
Both versions were supported before and after this PR, but I don't know if anyone has tested with v1 and these changes. The ImportError fallback at the top is what tries to load the older symbols (`unpadded` vs `varlen`)

I think flash-attn v2 is stable now, and with prebuilt wheels its easy to install. FWIW the entire xformers test suite now passes with flash-attn 2.0.8

**Pull request merged**
