### PR TITLE
Fixing issue#2134 Axolotl Crashes At The End Of Training If Base Model Is Local

### LINKED ISSUE #2134: Axolotl Crashes At The End Of Training If Base Model Is Local
### Please check that this issue hasn't been reported before.

- [X] I searched previous [Bug Reports](https://github.com/axolotl-ai-cloud/axolotl/labels/bug) didn't find any similar reports.

### Expected Behavior

The module should exit normally at the end of training.

### Current behaviour

In https://github.com/axolotl-ai-cloud/axolotl/blob/5726141c4eaeb61433f4da76fee1f023d97573f1/src/axolotl/train.py#L265-L287
we check if the base model is on the hub. However, the `catch` block expects a `(AttributeError, UnicodeDecodeError, RepositoryNotFoundError)`, but Huggingface actually raises `HFValidationError` when `cfg.base_model` is a local absolute path, because the path starts with a `/`, which is an invalid repository format. This error is not caught, and axolotl crashes.

### Steps to reproduce

Train any model where `base_model` points to a local absolute path on your hard drive.

### Config yaml

_No response_

### Possible solution

_No response_

### Which Operating Systems are you using?

- [ ] Linux
- [ ] macOS
- [ ] Windows

### Python Version

3.11

### axolotl branch-commit

main/5726141

### Acknowledgements

- [X] My issue title is concise, descriptive, and in title casing.
- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of axolotl.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

### PR DESCRIPTION
**Pull request by bursteratom**
# Description

Fix https://github.com/axolotl-ai-cloud/axolotl/issues/2134

### CODE REVIEW

**Comment by winglian** [comment]
What causes the hf validation error?

**Comment by bursteratom** [comment]
@winglian It happens when `cfg.base_model` is a local absolute path which starts with a `/`, which is an invalid repository format

**Comment by winglian** [comment]
> @winglian It happens when `cfg.base_model` is a local absolute path which starts with a `/`, which is an invalid repository format

It might make sense to check for a beginning slash and not go down the road of attempting to send it to hf in that case

**Comment by winglian** [comment]
@bursteratom Why were these lines needed when the datasets tag PR was created?

```python
            # Check to make sure the base model is from HuggingFace not a local directory
            hf_api = HfApi()
            hf_api.model_info(cfg.base_model)
```

**Comment by winglian** [comment]
This changeset in particular, since it wasn't needed before to create the model card

https://github.com/axolotl-ai-cloud/axolotl/pull/2101/files#diff-f582efd34d36848d0bb969652e9c1f42851eb9ec0c3490e7cdc637ed993ea0d6R265-R269

**Pull request merged**
