### PR TITLE
Feat: Convert attrdict to addict

### PR DESCRIPTION
**Pull request by NanoCode012**
`attrdict` is deprecated. We should swap to `addict`

- [x] Test the change

### CODE REVIEW

**Comment by NanoCode012** [comment]
Should also fix https://github.com/OpenAccess-AI-Collective/axolotl/issues/6

**Comment by NanoCode012** [comment]
Test using

```bash
accelerate launch scripts/finetune.py examples/lora-openllama-3b/config.yml
```

Print `cfg` becomes:

```py
{'base_model': 'openlm-research/open_llama_3b_600bt_preview', 'base_model_config': 'openlm-research/open_llama_3b_600bt_preview', 'model_type': 'LlamaForCausalLM', 'tokenizer_type': 'LlamaTokenizer', 'load_in_8bit': True, 'load_in_4bit': False, 'strict': False, 'push_dataset_to_hub': None, 'datasets': [{'path': 'teknium/GPT4-LLM-Cleaned', 'type': 'alpaca'}], 'dataset_prepared_path': 'last_run_prepared', 'val_set_size': 0.02, 'adapter': 'lora', 'lora_model_dir': None, 'sequence_len': 256, 'max_packed_sequence_len': None, 'lora_r': 8, 'lora_alpha': 16, 'lora_dropout': 0.0, 'lora_target_modules': ['gate_proj', 'down_proj', 'up_proj', 'q_proj', 'v_proj', 'k_proj', 'o_proj'], 'lora_fan_in_fan_out': None, 'wandb_project': None, 'wandb_watch': None, 'wandb_run_id': None, 'wandb_log_model': None, 'output_dir': './lora-out', 'batch_size': 16, 'micro_batch_size': 4, 'num_epochs': 3, 'optimizer': 'adamw_bnb_8bit', 'torchdistx_path': None, 'lr_scheduler': 'cosine', 'learning_rate': 0.0002, 'train_on_inputs': False, 'group_by_length': False, 'bf16': False, 'fp16': True, 'tf32': False, 'gradient_checkpointing': True, 'early_stopping_patience': None, 'resume_from_checkpoint': None, 'local_rank': None, 'logging_steps': 1, 'xformers_attention': None, 'flash_attention': None, 'gptq_groupsize': None, 'gptq_model_v1': None, 'warmup_steps': 10, 'eval_steps': 50, 'save_steps': None, 'debug': None, 'deepspeed': None, 'weight_decay': 0.0, 'fsdp': None, 'fsdp_config': None, 'special_tokens': {'bos_token': '<s>', 'eos_token': '</s>', 'unk_token': '<unk>'}}
```

Error due to default being `Dict` instead of `None`.

```bash
INFO:root:Starting trainer...
Traceback (most recent call last):
  File "/workspace/scripts/finetune.py", line 260, in <module>
    fire.Fire(train)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/workspace/scripts/finetune.py", line 248, in train
    trainer.train(resume_from_checkpoint=resume_from_checkpoint)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 1696, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer.py", line 1887, in _inner_training_loop
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer_callback.py", line 353, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/trainer_callback.py", line 397, in call_event
    result = getattr(callback, event)(
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/integrations.py", line 764, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/integrations.py", line 723, in setup
    combined_dict = {**args.to_sanitized_dict()}
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/training_args.py", line 1958, in to_sanitized_dict
    d = {**d, **{"train_batch_size": self.train_batch_size, "eval_batch_size": self.eval_batch_size}}
  File "/root/miniconda3/envs/py3.9/lib/python3.9/site-packages/transformers/training_args.py", line 1605, in eval_batch_size
    eval_batch_size = per_device_batch_size * max(1, self.n_gpu)
TypeError: unsupported operand type(s) for *: 'Dict' and 'int'
```

Two solutions:
- subclass, but lose shorthand `cfg.a.b.c` https://github.com/mewwts/addict#default-values
- use `cfg.get(key, default=None)`

**Comment by winglian** [comment]
what if we subclass it so that the `__missing__` method returns None? That matches our current setting of `AttrDefault(lambda: None, ...)` https://github.com/mewwts/addict/blob/master/addict/addict.py#L69-L72

edit: haha, that's what you were proposing!

**Comment by NanoCode012** [comment]
I do not know why the tests are not running. However, it passes locally.

- [x] Subclass
- [x] Add tests for subclass
- [x] Trains successfully for openllama

**Pull request merged**
