### PR TITLE
Bug fixing and patching

### PR DESCRIPTION
**Pull request by vietanh125**
In this commit:

- ChatML bug that leads to double <|im_end|> at the end has been fixed.
- Model card (REAME) showing "None dataset" has been fixed.
- Added input prompt printing before training for debugging purposes.

### CODE REVIEW

**Comment by casper-hansen** [comment]
Could you add an example of the prompt format before and after?

**Comment by vietanh125** [comment]
Sure. For ChatML format, I set the special tokens as follow
```
special_tokens:
    bos_token: "<s>"
    eos_token: "<|im_end|>"
    pad_token: "</s>"
    unk_token: "<unk>"

tokens:
    - "<|im_start|>"
    - "<|im_end|>"
```
and it results to an extra <|im_end|> before each user turn like this:
image

The issue is solved after setting `add_eos_token=False` on `ShareGPTPromptTokenizingStrategy`
image

**Comment by winglian** [comment]
hi @vietanh125 I can't edit this PR directly, but if you can run the pre-commit hooks, that would be great! `pre-commit run --all-files` thanks!

**Comment by vietanh125** [comment]
I ran it, there were some errors in pylint, mypy, and bandit but everything has passed when pushing.

**Comment by vietanh125** [comment]
I will close this PR and open one with more details about the issues.

**Pull request closed without merging**
